# -*- coding: utf-8 -*-
# vim: ft=yaml
---
###############################################################################
# Define all YAML node anchors
###############################################################################
.node_anchors:
  # `only` (also used for `except` where applicable)
  only_branch_master_parent_repo: &only_branch_master_parent_repo
    - 'master@saltstack-formulas/icinga2-formula'
  # `stage`
  stage_lint: &stage_lint 'lint'
  stage_release: &stage_release 'release'
  # `image`
  image_coala: &image_coala 'thomasboni/coala:latest'
  image_commitlint: &image_commitlint 'myii/ssf-commitlint:11'
  image_precommit: &image_precommit
    name: 'myii/ssf-pre-commit:2.9.2'
    entrypoint: ['/bin/bash', '-c']
  image_rubocop: &image_rubocop 'pipelinecomponents/rubocop:latest'
  image_semantic-release: &image_semanticrelease 'myii/ssf-semantic-release:15.14'

###############################################################################
# Define stages and global variables
###############################################################################
stages:
  - *stage_lint
  - *stage_release

###############################################################################
# `lint` stage: `commitlint`, `pre-commit`, `rubocop` (latest, failure allowed)
#               & `coala` (dev, failure allowed)
###############################################################################
coala:
  # allow_failure: true
  stage: *stage_lint
  image: *image_coala
  script:
    - 'coala --ci --files docs/README.rst --bears reSTLintBear
             --min-severity NORMAL --no-autoapply-warn'

###############################################################################
# `release` stage: `semantic-release`
###############################################################################
semantic-release:
  only: *only_branch_master_parent_repo
  stage: *stage_release
  image: *image_semanticrelease
  variables:
    MAINTAINER_TOKEN: '${GH_TOKEN}'
  script:
    # Update `AUTHORS.md`
    - '${HOME}/go/bin/maintainer contributor'
    # Run `semantic-release`
    - 'semantic-release'
