# -*- coding: utf-8 -*-
# vim: ft=yaml
---
name: 'Kitchen (Linux)'
'on': ['push', 'pull_request']

jobs:
  kitchen:
    runs-on: 'ubuntu-20.04'
    strategy:
      fail-fast: false
      matrix:
        instance:
          - default-debian-10-tiamat-py3
          - default-debian-9-tiamat-py3
          - default-ubuntu-2004-tiamat-py3
          - default-ubuntu-1804-tiamat-py3
          # - default-ubuntu-1604-tiamat-py3
          # - default-centos-8-tiamat-py3
          # - default-centos-7-tiamat-py3
          # - default-amazonlinux-2-tiamat-py3
          # - default-oraclelinux-8-tiamat-py3
          # - default-oraclelinux-7-tiamat-py3
    steps:
      - name: 'Check out code'
        uses: 'actions/checkout@v2'
      - name: 'Set up Bundler cache'
        uses: 'actions/cache@v1'
        with:
          path: 'vendor/bundle'
          key: "${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}"
          restore-keys: "${{ runner.os }}-gems-"
      - name: 'Install Bundler'
        run: |
          sudo gem install bundler \
            -v "$(grep -A 1 "BUNDLED WITH" Gemfile.lock | tail -n 1)" \
            --quiet --no-document
      - name: 'Run Bundler'
        run: |
          ruby --version
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: 'Run Test Kitchen'
        run: 'bundle exec kitchen verify ${{ matrix.instance }}'
        env:
          CHEF_LICENSE: 'accept-no-persist'
